# Generated by Django 3.2.7 on 2021-09-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventurename', models.CharField(max_length=200)),
                ('adventuretext', models.CharField(max_length=2000, null=True)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.CharField(default='there is no path', max_length=200)),
                ('pathtext', models.CharField(default='no path text', max_length=100)),
                ('photo_url', models.TextField(max_length=2000, null=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='findingyourway.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTableOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routename', models.CharField(default='there is no path', max_length=200)),
                ('routetext', models.CharField(default='no path text', max_length=100)),
                ('photo_url', models.TextField(max_length=2000, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='findingyourway.path')),
            ],
        ),
    ]
