# Generated by Django 3.2.7 on 2021-09-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventure', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='there is no path', max_length=200)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventures', to='findingyourway.adventure')),
            ],
        ),
    ]
