# Generated by Django 3.2.7 on 2021-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='text',
            field=models.CharField(default='no path text', max_length=100),
        ),
        migrations.AlterField(
            model_name='path',
            name='path',
            field=models.CharField(default='there is no path', max_length=200),
        ),
    ]
