# Generated by Django 3.2.7 on 2021-10-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ending',
            name='route',
        ),
        migrations.RemoveField(
            model_name='path',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='route',
            name='path',
        ),
    ]
