# Generated by Django 3.2.7 on 2021-09-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetableone',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathstabletwo', to='findingyourway.path'),
        ),
        migrations.CreateModel(
            name='RouteTableTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routename', models.CharField(default='there is no path', max_length=200)),
                ('routetext', models.CharField(default='no path text', max_length=100)),
                ('photo_url', models.TextField(max_length=2000, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathstablethree', to='findingyourway.path')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTableThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routename', models.CharField(default='there is no path', max_length=200)),
                ('routetext', models.CharField(default='no path text', max_length=100)),
                ('photo_url', models.TextField(max_length=2000, null=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='findingyourway.path')),
            ],
        ),
    ]
