# Generated by Django 3.2.7 on 2021-09-23 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='adventuretext',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='photo_url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='path',
            name='pathtext',
            field=models.CharField(default='no album title', max_length=100),
        ),
        migrations.AddField(
            model_name='path',
            name='photo_url',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
