# Generated by Django 3.2.7 on 2021-09-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0002_auto_20210927_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ending',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endings', to='findingyourway.route'),
        ),
    ]
