# Generated by Django 3.2.7 on 2021-09-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findingyourway', '0002_auto_20210923_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endingname', models.CharField(default='there is no ending', max_length=200)),
                ('endingtext', models.CharField(default='no path text', max_length=100)),
                ('photo_url', models.TextField(max_length=2000, null=True)),
                ('badending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodending', to='findingyourway.routetabletwo')),
                ('goodending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodending', to='findingyourway.routetableone')),
                ('neutralending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodending', to='findingyourway.routetablethree')),
            ],
        ),
    ]
